# ç”± VLESS è½¬æ¢ç”Ÿæˆçš„ Clash é…ç½®
# ç”Ÿæˆæ—¶é—´: 2025-05-15 22:55:37
# åŸå§‹é“¾æ¥: vless://84a91a76-1d66-45a8-8065-ed7fb7666a11@v2ray.tw-travel.online:13538?type=ws&path=%2Fv2ray&host=&security=tls&fp=chrome&alpn=#v2ray-q3ius0iq

proxies:
  - name: VLESS-v2ray.tw-travel.online:13538
  type: vless
  server: v2ray.tw-travel.online
  port: 13538
  uuid: 84a91a76-1d66-45a8-8065-ed7fb7666a11
  tls: True
  network: ws
  servername: 
  client-fingerprint: chrome
  ws-opts:
    path: /v2ray
    headers:
      Host: 

proxy-groups:
  - name: ğŸš€ Proxy
    type: select
    proxies:
      - VLESS-v2ray.tw-travel.online:13538

rules:
  - DOMAIN-SUFFIX,google.com,ğŸš€ Proxy
  - DOMAIN-KEYWORD,facebook,ğŸš€ Proxy
  - IP-CIDR,91.108.56.0/22,ğŸš€ Proxy
  - GEOIP,CN,DIRECT
  - MATCH,ğŸš€ Proxy
